import type { Lead, FollowUp, Activity, SalesRep, TeamAnalytics, PipelineStage } from "./types";

export const demoSalesReps: SalesRep[] = [
  {
    id: "rep_elena",
    fullName: "Elena Torres",
    email: "elena@salesco.example.test",
    role: "Senior Account Executive",
    quotaAttainment: 94,
    dealsWon: 12,
    pipelineValue: 485000,
  },
  {
    id: "rep_marcus",
    fullName: "Marcus Webb",
    email: "marcus@salesco.example.test",
    role: "Account Executive",
    quotaAttainment: 78,
    dealsWon: 8,
    pipelineValue: 312000,
  },
  {
    id: "rep_sana",
    fullName: "Sana Iqbal",
    email: "sana@salesco.example.test",
    role: "SDR Team Lead",
    quotaAttainment: 112,
    dealsWon: 6,
    pipelineValue: 198000,
  },
];

export const demoLeads: Lead[] = [
  {
    id: "lead_001",
    fullName: "David Park",
    company: "Northwind Logistics",
    title: "VP Operations",
    email: "d.park@northwind-logistics.example.test",
    phone: "+1-415-555-0101",
    source: "inbound",
    status: "proposal",
    aiScore: 92,
    aiScoreConfidence: "high",
    aiScoreLastUpdatedAt: "2026-06-07T14:30:00Z",
    aiScoreFactors: [
      { label: "High deal value ($84K)", impact: "positive", weight: 30 },
      { label: "Recent engagement (7d ago)", impact: "positive", weight: 25 },
      { label: "Enterprise account", impact: "positive", weight: 20 },
      { label: "Proposal stage — close proximity", impact: "positive", weight: 17 },
    ],
    aiRiskFlags: [],
    dealValue: 84000,
    ownerId: "rep_elena",
    createdAt: "2026-05-14T09:30:00Z",
    lastContactedAt: "2026-06-07T14:15:00Z",
    nextFollowUpId: "fu_001",
    tags: ["logistics", "enterprise", "warm"],
  },
  {
    id: "lead_002",
    fullName: "Angela Cross",
    company: "Meridian Health Partners",
    title: "Director of IT",
    email: "a.cross@meridian-health.example.test",
    phone: "+1-312-555-0187",
    source: "event",
    status: "qualified",
    aiScore: 87,
    aiScoreConfidence: "medium",
    aiScoreLastUpdatedAt: "2026-06-08T11:00:00Z",
    aiScoreFactors: [
      { label: "Enterprise healthcare deal ($126K)", impact: "positive", weight: 35 },
      { label: "Event-sourced — warm inbound signal", impact: "positive", weight: 20 },
      { label: "Director-level champion", impact: "positive", weight: 18 },
      { label: "Budget unconfirmed", impact: "negative", weight: 14 },
    ],
    aiRiskFlags: ["budget_unconfirmed"],
    dealValue: 126000,
    ownerId: "rep_elena",
    createdAt: "2026-05-20T11:00:00Z",
    lastContactedAt: "2026-06-08T10:30:00Z",
    nextFollowUpId: "fu_002",
    tags: ["healthcare", "enterprise", "needs_security_review"],
  },
  {
    id: "lead_003",
    fullName: "Raj Mehta",
    company: "Finova Capital",
    title: "Head of Sales Operations",
    email: "r.mehta@finova-capital.example.test",
    phone: "+1-212-555-0234",
    source: "referral",
    status: "contacted",
    aiScore: 76,
    aiScoreConfidence: "medium",
    aiScoreLastUpdatedAt: "2026-06-05T09:15:00Z",
    aiScoreFactors: [
      { label: "Referral source — higher intent", impact: "positive", weight: 28 },
      { label: "Fintech vertical fit", impact: "positive", weight: 22 },
      { label: "Head of Sales Ops (buyer persona)", impact: "positive", weight: 18 },
      { label: "Slow response history", impact: "negative", weight: 20 },
      { label: "Multiple stakeholders unaligned", impact: "negative", weight: 12 },
    ],
    aiRiskFlags: ["slow_response", "multiple_stakeholders"],
    dealValue: 65000,
    ownerId: "rep_marcus",
    createdAt: "2026-05-28T16:45:00Z",
    lastContactedAt: "2026-06-05T09:00:00Z",
    nextFollowUpId: "fu_003",
    tags: ["fintech", "midmarket", "needs_demo"],
  },
  {
    id: "lead_004",
    fullName: "Claire Bishop",
    company: "Apex Manufacturing",
    title: "COO",
    email: "c.bishop@apex-mfg.example.test",
    phone: "+1-615-555-0412",
    source: "outbound",
    status: "new",
    aiScore: 64,
    aiScoreConfidence: "low",
    aiScoreLastUpdatedAt: "2026-06-09T08:30:00Z",
    aiScoreFactors: [
      { label: "COO title — decision-maker", impact: "positive", weight: 22 },
      { label: "Manufacturing vertical fit", impact: "positive", weight: 16 },
      { label: "Cold outbound — no intent signal", impact: "negative", weight: 30 },
      { label: "No engagement history", impact: "negative", weight: 20 },
      { label: "Low deal value ($48K)", impact: "negative", weight: 12 },
    ],
    aiRiskFlags: ["low_engagement", "no_pain_identified"],
    dealValue: 48000,
    ownerId: "rep_sana",
    createdAt: "2026-06-09T08:15:00Z",
    lastContactedAt: null,
    nextFollowUpId: null,
    tags: ["manufacturing", "cold_outbound"],
  },
  {
    id: "lead_005",
    fullName: "Tomas Berg",
    company: "Skybridge Aviation",
    title: "VP Engineering",
    email: "t.berg@skybridge-aviation.example.test",
    phone: "+1-206-555-0199",
    source: "partner",
    status: "proposal",
    aiScore: 91,
    aiScoreConfidence: "high",
    aiScoreLastUpdatedAt: "2026-06-08T16:15:00Z",
    aiScoreFactors: [
      { label: "Largest deal value ($210K)", impact: "positive", weight: 35 },
      { label: "Enterprise partner referral", impact: "positive", weight: 25 },
      { label: "Legal approved — contract ready", impact: "positive", weight: 20 },
      { label: "VP-level champion engaged", impact: "positive", weight: 11 },
    ],
    aiRiskFlags: [],
    dealValue: 210000,
    ownerId: "rep_elena",
    createdAt: "2026-04-30T13:00:00Z",
    lastContactedAt: "2026-06-08T16:00:00Z",
    nextFollowUpId: "fu_005",
    tags: ["aerospace", "enterprise", "hot"],
  },
  {
    id: "lead_006",
    fullName: "Priya Nair",
    company: "LegalCore Associates",
    title: "Managing Partner",
    email: "p.nair@legalcore.example.test",
    phone: "+1-617-555-0334",
    source: "inbound",
    status: "qualified",
    aiScore: 83,
    aiScoreConfidence: "medium",
    aiScoreLastUpdatedAt: "2026-06-06T12:00:00Z",
    aiScoreFactors: [
      { label: "Managing partner — buyer authority", impact: "positive", weight: 28 },
      { label: "Inbound source — high intent", impact: "positive", weight: 24 },
      { label: "Compliance review pending", impact: "negative", weight: 22 },
      { label: "Mid-range deal ($72K)", impact: "negative", weight: 9 },
    ],
    aiRiskFlags: ["compliance_review_pending"],
    dealValue: 72000,
    ownerId: "rep_marcus",
    createdAt: "2026-05-22T14:20:00Z",
    lastContactedAt: "2026-06-06T11:45:00Z",
    nextFollowUpId: "fu_006",
    tags: ["legal", "compliance", "warm"],
  },
  {
    id: "lead_007",
    fullName: "James Okonkwo",
    company: "Gridpoint Energy",
    title: "Chief Digital Officer",
    email: "j.okonkwo@gridpoint-energy.example.test",
    phone: "+1-832-555-0277",
    source: "event",
    status: "won",
    aiScore: 95,
    aiScoreConfidence: "high",
    aiScoreLastUpdatedAt: "2026-06-01T09:30:00Z",
    aiScoreFactors: [
      { label: "Closed-won validation signal", impact: "positive", weight: 40 },
      { label: "Enterprise deal ($156K)", impact: "positive", weight: 30 },
      { label: "CDO-level executive champion", impact: "positive", weight: 15 },
      { label: "Onboarding scheduled", impact: "positive", weight: 10 },
    ],
    aiRiskFlags: [],
    dealValue: 156000,
    ownerId: "rep_elena",
    createdAt: "2026-04-10T10:00:00Z",
    lastContactedAt: "2026-06-01T09:00:00Z",
    nextFollowUpId: null,
    tags: ["energy", "enterprise", "closed"],
  },
  {
    id: "lead_008",
    fullName: "Fatima Hassan",
    company: "MedSupply Direct",
    title: "Director of Procurement",
    email: "f.hassan@medsupply-direct.example.test",
    phone: "+1-702-555-0611",
    source: "inbound",
    status: "lost",
    aiScore: 68,
    aiScoreConfidence: "low",
    aiScoreLastUpdatedAt: "2026-05-28T15:15:00Z",
    aiScoreFactors: [
      { label: "Inbound source — had intent", impact: "positive", weight: 20 },
      { label: "Healthcare vertical fit", impact: "positive", weight: 18 },
      { label: "Lost to competitor — churn risk", impact: "negative", weight: 30 },
      { label: "Pricing objection unresolved", impact: "negative", weight: 20 },
      { label: "Small deal ($39K)", impact: "negative", weight: 12 },
    ],
    aiRiskFlags: ["went_with_competitor", "pricing_objection"],
    dealValue: 39000,
    ownerId: "rep_sana",
    createdAt: "2026-05-01T08:30:00Z",
    lastContactedAt: "2026-05-28T15:00:00Z",
    nextFollowUpId: null,
    tags: ["healthcare", "small_business", "lost"],
  },
];

export const demoFollowUps: FollowUp[] = [
  {
    id: "fu_001", leadId: "lead_001", type: "call",
    scheduledFor: "2026-06-11T10:00:00Z", priority: "high",
    title: "Walk through proposal revisions",
    notes: "David wants to discuss multi-year pricing and onboarding timeline.",
    completed: false, completedAt: null,
  },
  {
    id: "fu_002", leadId: "lead_002", type: "demo",
    scheduledFor: "2026-06-12T14:00:00Z", priority: "high",
    title: "Security architecture demo for IT team",
    notes: "Angela's CISO is joining. Focus on data residency and encryption.",
    completed: false, completedAt: null,
  },
  {
    id: "fu_003", leadId: "lead_003", type: "email",
    scheduledFor: "2026-06-10T09:00:00Z", priority: "medium",
    title: "Send case study — fintech compliance",
    notes: "Raj asked for fintech-specific examples. Attach SOC 2 docs.",
    completed: false, completedAt: null,
  },
  {
    id: "fu_004", leadId: "lead_001", type: "call",
    scheduledFor: "2026-06-03T11:00:00Z", priority: "high",
    title: "Initial proposal review",
    notes: "David liked the pricing model but wants adjustments.",
    completed: true, completedAt: "2026-06-03T11:45:00Z",
  },
  {
    id: "fu_005", leadId: "lead_005", type: "proposal_send",
    scheduledFor: "2026-06-11T08:00:00Z", priority: "high",
    title: "Send final SOW and contract",
    notes: "Legal approved terms. Tomas ready to sign.",
    completed: false, completedAt: null,
  },
  {
    id: "fu_006", leadId: "lead_006", type: "meeting",
    scheduledFor: "2026-06-13T15:00:00Z", priority: "medium",
    title: "Compliance alignment meeting",
    notes: "Priya wants to walk through data handling before committing.",
    completed: false, completedAt: null,
  },
  {
    id: "fu_007", leadId: "lead_003", type: "call",
    scheduledFor: "2026-06-02T16:00:00Z", priority: "medium",
    title: "Initial discovery call",
    notes: "Raj outlined pain points around pipeline visibility.",
    completed: true, completedAt: "2026-06-02T16:40:00Z",
  },
];

export const demoActivities: Activity[] = [
  { id: "act_001", leadId: "lead_001", type: "call", timestamp: "2026-06-07T14:15:00Z", summary: "Discussed proposal feedback. Positive on pricing, wants minor scope adjustments.", outcome: "positive" },
  { id: "act_002", leadId: "lead_002", type: "meeting", timestamp: "2026-06-08T10:30:00Z", summary: "Security review scheduled. CISO to attend. Angela confirmed budget exists but procurement cycle is long.", outcome: "neutral" },
  { id: "act_003", leadId: "lead_005", type: "email", timestamp: "2026-06-08T16:00:00Z", summary: "Tomas confirmed legal sign-off. Moving to contract stage.", outcome: "positive" },
  { id: "act_004", leadId: "lead_003", type: "call", timestamp: "2026-06-05T09:00:00Z", summary: "Raj slow to respond. Left voicemail. Concern about stakeholder alignment.", outcome: "negative" },
  { id: "act_005", leadId: "lead_007", type: "email", timestamp: "2026-06-01T09:00:00Z", summary: "Closed-won confirmation. Onboarding kickoff scheduled for June 16.", outcome: "positive" },
  { id: "act_006", leadId: "lead_006", type: "email", timestamp: "2026-06-06T11:45:00Z", summary: "Priya acknowledged compliance materials. Scheduling follow-up meeting.", outcome: "positive" },
  { id: "act_007", leadId: "lead_008", type: "call", timestamp: "2026-05-28T15:00:00Z", summary: "Lost to competitor on pricing. Fatima open to revisiting next quarter.", outcome: "negative" },
];

export const demoPipelineStages: PipelineStage[] = [
  { id: "stage_new", name: "New", order: 1, dealCount: 8, totalValue: 312000 },
  { id: "stage_contacted", name: "Contacted", order: 2, dealCount: 6, totalValue: 268000 },
  { id: "stage_qualified", name: "Qualified", order: 3, dealCount: 5, totalValue: 445000 },
  { id: "stage_proposal", name: "Proposal", order: 4, dealCount: 3, totalValue: 378000 },
  { id: "stage_closing", name: "Closing", order: 5, dealCount: 2, totalValue: 294000 },
];

export const demoAnalytics: TeamAnalytics = {
  totalLeads: 148,
  qualifiedLeads: 37,
  pipelineValue: 1697000,
  avgDealSize: 73780,
  conversionRate: 24,
  tasksDueToday: 8,
  overdueTasks: 3,
  winRate: 32,
};
